### ISSUE TITLE
Cannot start Zinnia: Command failed with exit code

### ISSUE THREAD

**Issue by btcetcx** [filecoin-station/zinnia#484] opened 2024-02-06 17:20 UTC
![Uploading 微信截图_20240207011352.png…]()

**Comment by juliangruber** [comment] 2024-02-06 21:42
can you please try uploading the picture again?

**Comment by bajtos** [comment] 2024-02-08 12:51
Closing as a duplicate of https://github.com/filecoin-station/zinnia/issues/483

**Closed by bajtos** 2024-02-08 12:51 UTC
